name: version-and-publish-packages

# Events
on:
  pull_request:
    # Only For Merged PRs
    types:
      - closed
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - development

jobs:
  version-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: tushar1998/ultimate-pnpm:lts

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIT_USERNAME: githubactions
      GIT_EMAIL: mistry.tushar98@gmail.com

    steps:
      - name: Checkout
        run: actions/checkout@v2
   
      - name: Install Packages Node Modules
        run: pnpm install --forzen-lockfile
    
